from logic_utils import check_guess, get_range_for_difficulty, update_score, parse_guess

# (All test cases generated by Claude code)

# ---------------------------------------------------------------------------
# Bug 11 — check_guess must return a (outcome, message) tuple, not a string
# ---------------------------------------------------------------------------

def test_winning_guess_returns_tuple():
    result = check_guess(50, 50)
    assert isinstance(result, tuple), "check_guess should return a (outcome, message) tuple"
    assert result[0] == "Win"

def test_guess_too_high_returns_tuple():
    result = check_guess(60, 50)
    assert isinstance(result, tuple), "check_guess should return a tuple"
    assert result[0] == "Too High"

def test_guess_too_low_returns_tuple():
    result = check_guess(40, 50)
    assert isinstance(result, tuple), "check_guess should return a tuple"
    assert result[0] == "Too Low"


# ---------------------------------------------------------------------------
# Bug 2 — "Too High" hint must direct the player LOWER, not HIGHER
# ---------------------------------------------------------------------------

def test_too_high_message_says_lower():
    _, message = check_guess(80, 50)
    assert "lower" in message.lower(), (
        f"When guess is too high, message should say 'lower', got: '{message}'"
    )

def test_too_low_message_says_higher():
    _, message = check_guess(20, 50)
    assert "higher" in message.lower(), (
        f"When guess is too low, message should say 'higher', got: '{message}'"
    )


# ---------------------------------------------------------------------------
# Bug 1 — Hard difficulty range must be wider (harder) than Normal
# ---------------------------------------------------------------------------

def test_hard_range_wider_than_normal():
    normal_low, normal_high = get_range_for_difficulty("Normal")
    hard_low, hard_high = get_range_for_difficulty("Hard")
    assert (hard_high - hard_low) > (normal_high - normal_low), (
        f"Hard range ({hard_low}–{hard_high}) should be wider than "
        f"Normal ({normal_low}–{normal_high})"
    )

def test_easy_range_narrower_than_normal():
    normal_low, normal_high = get_range_for_difficulty("Normal")
    easy_low, easy_high = get_range_for_difficulty("Easy")
    assert (easy_high - easy_low) < (normal_high - normal_low), (
        f"Easy range ({easy_low}–{easy_high}) should be narrower than "
        f"Normal ({normal_low}–{normal_high})"
    )


# ---------------------------------------------------------------------------
# Bug 6 — check_guess must use numeric comparison, not lexicographic strings
# ---------------------------------------------------------------------------

def test_nine_less_than_one_hundred():
    # "9" > "100" lexicographically, but 9 < 100 numerically.
    # A string-compare bug would return "Too High" here — should be "Too Low".
    outcome, _ = check_guess(9, 100)
    assert outcome == "Too Low", (
        f"9 < 100 numerically, expected 'Too Low' but got '{outcome}' "
        f"(possible string/lexicographic comparison bug)"
    )

def test_check_guess_consistent_int_types():
    # Passing both args as ints should never raise TypeError or give wrong result
    outcome, _ = check_guess(1, 200)
    assert outcome == "Too Low"
    outcome, _ = check_guess(200, 1)
    assert outcome == "Too High"


# ---------------------------------------------------------------------------
# Bug 7 — win score must not over-deduct via (attempt_number + 1)
# ---------------------------------------------------------------------------

def test_win_on_first_attempt_scores_90():
    # attempt 1: points = 100 - 10*1 = 90  (bug had 100 - 10*2 = 80)
    result = update_score(0, "Win", 1)
    assert result == 90, f"Expected 90 for first-attempt win, got {result}"

def test_win_on_second_attempt_scores_80():
    result = update_score(0, "Win", 2)
    assert result == 80, f"Expected 80 for second-attempt win, got {result}"

def test_earlier_win_scores_higher_than_later_win():
    score_attempt_1 = update_score(0, "Win", 1)
    score_attempt_2 = update_score(0, "Win", 2)
    assert score_attempt_1 > score_attempt_2, (
        "Winning on attempt 1 should outscore winning on attempt 2"
    )


# ---------------------------------------------------------------------------
# Bug 8 — wrong guesses must never award points (even on even attempt numbers)
# ---------------------------------------------------------------------------

def test_too_high_even_attempt_does_not_award_points():
    # Bug gave +5 when attempt_number % 2 == 0
    score = update_score(100, "Too High", 2)
    assert score < 100, (
        f"A wrong 'Too High' guess on an even attempt should lose points, got {score}"
    )

def test_too_high_odd_attempt_loses_points():
    score = update_score(100, "Too High", 1)
    assert score < 100

def test_too_low_loses_points():
    score = update_score(100, "Too Low", 1)
    assert score < 100


# ---------------------------------------------------------------------------
# Bug 9 / 10 — logic_utils functions must be implemented (no NotImplementedError)
# ---------------------------------------------------------------------------

def test_get_range_for_difficulty_is_implemented():
    try:
        get_range_for_difficulty("Normal")
    except NotImplementedError:
        assert False, "get_range_for_difficulty raised NotImplementedError — not implemented"

def test_parse_guess_is_implemented():
    try:
        parse_guess("42")
    except NotImplementedError:
        assert False, "parse_guess raised NotImplementedError — not implemented"

def test_check_guess_is_implemented():
    try:
        check_guess(50, 50)
    except NotImplementedError:
        assert False, "check_guess raised NotImplementedError — not implemented"

def test_update_score_is_implemented():
    try:
        update_score(0, "Win", 1)
    except NotImplementedError:
        assert False, "update_score raised NotImplementedError — not implemented"
